### ISSUE TITLE
 it does't work

### ISSUE THREAD

**Issue by lcxw** [zwStar/meituan-backend#1]
$ cnpm i
√ Installed 22 packages
√ Linked 0 latest versions
√ Run 0 scripts
√ All packages installed (used 18ms, speed 0B/s, json 0(0B), tarball 0B)

wang@DESKTOP-DTCRCD3 MINGW64 /f/githome/nodejs/vue/meituan-backend (master)
$ npm run dev

> meituan-back@1.0.1 dev F:\githome\nodejs\vue\meituan-backend
> cross-env NODE_ENV=dev nodemon  index.js

[nodemon] 1.17.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
F:\githome\nodejs\vue\meituan-backend\node_modules\_express@4.16.3@express\lib\router\route.js:202
        throw new Error(msg);
        ^

Error: Route.post() requires a callback function but got a [object Undefined]
    at Route.(anonymous function) [as post] (F:\githome\nodejs\vue\meituan-backend\node_modules\_express@4.16.3@express\lib\router\route.js:202:15)
    at Function.proto.(anonymous function) [as post] (F:\githome\nodejs\vue\meituan-backend\node_modules\_express@4.16.3@express\lib\router\index.js:510:19)
    at Object.<anonymous> (F:/githome/nodejs/vue/meituan-backend/routes/v1.js:29:8)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at loader (F:\githome\nodejs\vue\meituan-backend\node_modules\_babel-register@6.26.0@babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (F:\githome\nodejs\vue\meituan-backend\node_modules\_babel-register@6.26.0@babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (F:/githome/nodejs/vue/meituan-backend/routes/index.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at loader (F:\githome\nodejs\vue\meituan-backend\node_modules\_babel-register@6.26.0@babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (F:\githome\nodejs\vue\meituan-backend\node_modules\_babel-register@6.26.0@babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:566:32)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by zwStar** [comment]
不好意思，已经修复
