### ISSUE TITLE
后端项目启动报错

### ISSUE THREAD

**Issue by xspurs** [zwStar/meituan-backend#2]
报错信息：
```JavaScript
> cross-env NODE_ENV=dev nodemon  index.js

events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: spawn nodemon ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:114:19)
    at Function.Module.runMain (module.js:692:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:207:12)
    at onErrorNT (internal/child_process.js:379:16)
    [... lines matching original stack trace ...]
    at bootstrap_node.js:666:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meituan-back@1.0.1 dev: `cross-env NODE_ENV=dev nodemon  index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meituan-back@1.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

可以帮忙看下么，想本地跑一下

**Comment by weiyanan95** [comment]
我运行也这样。请问解决了吗

**Comment by xspurs** [comment]
还没有解决

**Comment by eyangba** [comment]
把 package.json 中的 cross-env NODE_ENV=dev nodemon  index.js 改成 cross-env NODE_ENV=development node index.js 即可。

**Comment by xspurs** [comment]
"dev": "cross-env NODE_ENV=development node build/dev-server.js"
这个是对应的package.json中的配置信息，按eyangba的建议修改后执行 npm run dev 仍然异常，没有解决

**Comment by q1057805963** [comment]
解决了吗

**Comment by xspurs** [comment]
> 解决了吗

没有，后来没有再关注了

**Comment by oo6890049** [comment]
1.把 package.json 中的 cross-env NODE_ENV=dev nodemon index.js 改成 cross-env NODE_ENV=development node index.js 
2.npm install cross-env --save-dev

**Comment by Resen4983** [comment]
或者你安装下nodemon这个模块`npm install nodemon --dev`

**Comment by zhangaofei** [comment]
楼上的方法都不行，还有办法吗
